Fixed critical accessibility errors
kausaltech/kausal-watch-ui pull request #238
Opened 2023-12-12 07:19 UTC by lilia1891

fixed critical accessibility html errors.
Related Asana task https://app.asana.com/0/1202880927552397/1206128477196469/f

2023-12-13 08:31 UTC, terotik requested changes

2023-12-13 08:31 UTC, terotik commented on components/indicators/IndicatorProgressBar.js
Same as above. Maybe better to have this solution in `Switch` component

2023-12-13 18:28 UTC, lilia1891 commented on components/insight/InsightFilter.js
>      </div>
I tried for & id combination but for some reason Axe isn’t satisfied with it

2023-12-13 18:29 UTC, lilia1891 commented on components/indicators/IndicatorNormalizationSelect.tsx
Thanks! Modified Switch component.

2023-12-15 08:12 UTC, terotik approved these changes

2023-12-15 09:49 UTC, merged